version: '3.7'
services:
  web-app:
    environment:
      EMAIL_SENDER_USERNAME: "some.user@somedomain.com"
      EMAIL_SENDER_PASSWORD: "somepassword"
      EMAIL_SENDER_HOST: "some.smtp.somedomain.com"
      SSL_TRUST_HOST: "bogus"
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      PROXY_IP: localhost
  gtas-scheduler:
    environment:
      EMAIL_SENDER_USERNAME: "some.user@somedomain.com"
      EMAIL_SENDER_PASSWORD: "somepassword"
      EMAIL_SENDER_HOST: "some.smtp.somedomain.com"
      SSL_TRUST_HOST: "bogus"
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      PROXY_IP: localhost
    volumes:
      - type: bind
        source: ./gtas-data
        target: /usr/local/gtas-data
        consistency: consistent
