version: '3.7'
services:
  web-app:
    environment:
      EMAIL_SENDER_USERNAME: "some.user@somedomain.com"
      EMAIL_SENDER_PASSWORD: "somepassword"
      EMAIL_SENDER_HOST: "some.smtp.somedomain.com"
      SSL_TRUST_HOST: "bogus"
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      ADDITIONAL_PROCESSING_THIRD_PARTY: "false"
      ADDITIONAL_PROCESSING_RAW: "false"
      ADDITIONAL_PROCESSING_RULES: "false"
      PROXY_IP: localhost
  activemq:
    ports:
      - 61616:61616
      - 8161:8161
  gtas-scheduler:
    environment:
      EMAIL_SENDER_USERNAME: "some.user@somedomain.com"
      EMAIL_SENDER_PASSWORD: "somepassword"
      EMAIL_SENDER_HOST: "some.smtp.somedomain.com"
      SSL_TRUST_HOST: "bogus"
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      ADDITIONAL_PROCESSING_THIRD_PARTY: "false"
      ADDITIONAL_PROCESSING_RAW: "false"
      ADDITIONAL_PROCESSING_RULES: "false"
      PROXY_IP: localhost
    volumes:
      - type: bind
        source: ./gtas-data
        target: /usr/local/gtas-data
        consistency: consistent
secrets:
  elastic-key:
    file: ./gtas-parent/gtas-commons/certs/elasticsearch-node1.key
  elastic-ca:
    file: ./gtas-parent/gtas-commons/certs/elastic-ca.crt
  elastic-cert:
    file: ./gtas-parent/gtas-commons/certs/elasticsearch-node1.crt
  webapp-cert:
    file: ./gtas-parent/gtas-commons/certs/wcogtas.org.crt
  webapp-key:
    file: ./gtas-parent/gtas-commons/certs/wcogtas.org.key
  kibana-crt:
    file: ./gtas-parent/gtas-commons/certs/kibana.crt
  kibana-key:
    file: ./gtas-parent/gtas-commons/certs/kibana.key
