version: '3.7'
services:
  http-proxy:
    secrets:
      - source: webapp-cert
        target: /wcogtas.org.crt
      - source: webapp-key
        target: /wcogtas.org.key
    environment:
      BOOTSTRAP_PATH: '/run/secrets/elastic-bootstrap-password'
  web-app:
    environment:
      EMAIL_SENDER_USERNAME: ""
      EMAIL_SENDER_PASSWORD: ""
      EMAIL_SENDER_HOST: ""
      SSL_TRUST_HOST: ""
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      PROXY_IP: localhost
      BOOTSTRAP_PATH: "/run/secrets/elastic-bootstrap-password"
      MYSQL_USER_PATH: "/run/secrets/mysql_webapp_user"
      MYSQL_PASSWORD_PATH: "/run/secrets/mysql_webapp_password"
      NEO4J_USER_PATH: "/run/secrets/webapp_neo4j_user"
      NEO4J_PASSWORD_PATH: "/run/secrets/webapp_neo4j_password"
    secrets:
      - source: webapp-cert
        target: /usr/local/tomcat/conf/wcogtas.org.crt
      - source: webapp-key
        target: /usr/local/tomcat/conf/wcogtas.org.key
      - source: elastic-cert
        target: /usr/local/tomcat/conf/elasticsearch-node1.crt
      - source: elastic-key
        target: /usr/local/tomcat/conf/elasticsearch-node1.key
      - source: elastic-ca
        target: /usr/local/tomcat/conf/elastic-ca.crt
  logstash:
    environment:
      XPACK_MONITORING_ELASTICSEARCH_SSL_CERTIFICATEAUTHORITY: /run/secrets/elastic-ca
  elasticsearch:
    secrets:
      - source: elastic-ca
        target: /usr/share/elasticsearch/config/certs/elasticsearch/elastic-ca.crt
      - source: elastic-cert
        target: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch-node1.crt
      - source: elastic-key
        target: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch-node1.key
  kibana:
    secrets:
      - source: elastic-ca
        target: /etc/kibana/config/ca.crt
      - source: kibana-crt
        target: /etc/kibana/config/kibana.crt
      - source: kibana-key
        target: /etc/kibana/config/kibana.key
  gtas-scheduler:
    environment:
      EMAIL_SENDER_USERNAME: ""
      EMAIL_SENDER_PASSWORD: ""
      EMAIL_SENDER_HOST: ""
      SSL_TRUST_HOST: ""
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      PROXY_IP: localhost
      MYSQL_USER_PATH: "/run/secrets/mysql_processor_user"
      MYSQL_PASSWORD_PATH: "/run/secrets/mysql_processor_password"
      NEO4J_USER_PATH: "/run/secrets/webapp_neo4j_user"
      NEO4J_PASSWORD_PATH: "/run/secrets/webapp_neo4j_password"
    volumes:
      - type: bind
        source: ./gtas-data
        target: /usr/local/gtas-data
        consistency: consistent
  elk-setup:
    environment:
      LOGSTASH_PASSWORD_PATH: '/run/secrets/logstash-keystore-password' 
      MYSQL_USER_PATH: '/run/secrets/mysql-logstash-user'
      MYSQL_PASSWORD_PATH: '/run/secrets/mysql-logstash-password'
      KIBANA_PASSWORD_PATH: '/run/secrets/elasticsearch-kibana-password'
      BOOTSTRAP_PATH: '/run/secrets/elastic-bootstrap-password'
      ELASTIC_PATH: '/run/secrets/elastic-password'
  
  etl-job:
    environment:
      DB_HOSTNAME: mariadb
      NEO4J_USER_PATH: '/run/secrets/etl_neo4j_user'
      NEO4J_PASSWORD_PATH: '/run/secrets/etl_neo4j_password'
      MYSQL_USER_PATH: '/run/secrets/mysql_etl_user'
      MYSQL_PASSWORD_PATH: '/run/secrets/mysql_etl_password'
secrets:
  elastic-key:
    file: ./gtas-parent/gtas-commons/certs/elasticsearch-node1.key
  elastic-ca:
    file: ./gtas-parent/gtas-commons/certs/elastic-ca.crt
  elastic-cert:
    file: ./gtas-parent/gtas-commons/certs/elasticsearch-node1.crt
  webapp-cert:
    file: ./gtas-parent/gtas-commons/certs/wcogtas.org.crt
  webapp-key:
    file: ./gtas-parent/gtas-commons/certs/wcogtas.org.key
  kibana-crt:
    file: ./gtas-parent/gtas-commons/certs/kibana.crt
  kibana-key:
    file: ./gtas-parent/gtas-commons/certs/kibana.key