version: '3.7'
services:
  web-app:
    environment:
      EMAIL_SENDER_USERNAME: "some.user@somedomain.com"
      EMAIL_SENDER_PASSWORD: "somepassword"
      EMAIL_SENDER_HOST: "some.smtp.somedomain.com"
      SSL_TRUST_HOST: "bogus"
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      ADDITIONAL_PROCESSING_THIRD_PARTY: "false"
      ADDITIONAL_PROCESSING_RAW: "false"
      ADDITIONAL_PROCESSING_RULES: "false"
      PROXY_IP: localhost
  activemq:
    ports:
      - 61616:61616
      - 8161:8161
  gtas-scheduler:
    environment:
      EMAIL_SENDER_USERNAME: "some.user@somedomain.com"
      EMAIL_SENDER_PASSWORD: "somepassword"
      EMAIL_SENDER_HOST: "some.smtp.somedomain.com"
      SSL_TRUST_HOST: "bogus"
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      ADDITIONAL_PROCESSING_THIRD_PARTY: "false"
      ADDITIONAL_PROCESSING_RAW: "false"
      ADDITIONAL_PROCESSING_RULES: "false"
      PROXY_IP: localhost
    volumes:
      - type: bind
        source: ./gtas-data
        target: /usr/local/gtas-data
        consistency: consistent
  neo4j:
    environment:
      NEO4J_AUTH: "neo4j/admin"
      NEO4J_dbms_connector_bolt_advertised__address: localhost:7687
      NEO4J_dbms_connectors_default__advertised__address: localhost
secrets:
  kibana-crt:
    file: ./gtas-parent/gtas-commons/certs/kibana.crt
  kibana-key:
    file: ./gtas-parent/gtas-commons/certs/kibana.key
