version: '3.7'
services:
  http-proxy:
    deploy:
      labels:
        kompose.image-pull-policy: "Always" 
      placement:
        constraints:
          - node.labels.role == node-a
    environment:
      BOOTSTRAP_PATH: '/run/secrets/elastic-bootstrap-password/elastic-bootstrap-password'
    volumes:
      - ./gtas-parent/gtas-commons/certs:/
  web-app:
    environment:
      JAVA_TOOL_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport"
      JAVA_OPTS: "-Xms4g -Xmx8g -XX:MaxPermSize=16g -Duser.timezone=UTC"
      EMAIL_SENDER_USERNAME: ""
      EMAIL_SENDER_PASSWORD: ""
      EMAIL_SENDER_HOST: ""
      SSL_TRUST_HOST: ""
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      PROXY_IP: ""
      BOOTSTRAP_PATH: "/run/secrets/elastic-bootstrap-password/elastic-bootstrap-password"
      MYSQL_USER_PATH: "/run/secrets/mysql_webapp_user/mysql_webapp_user"
      MYSQL_PASSWORD_PATH: "/run/secrets/mysql_webapp_password/mysql_webapp_password"
      NEO4J_USER_PATH: "/run/secrets/webapp_neo4j_user/webapp_neo4j_user"
      NEO4J_PASSWORD_PATH: "/run/secrets/webapp_neo4j_password/webapp_neo4j_password"
    deploy:
      labels:
        kompose.image-pull-policy: "Always"
      placement:
        constraints:
          - node.labels.role == node-a
    volumes:
      - ./gtas-parent/gtas-commons/certs:/usr/local/tomcat/conf
  gtas-scheduler:
    environment:
      JAVA_TOOL_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport"
      JAVA_OPTS: "-Xms8000m -Xmx16000m -Duser.timezone=UTC -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"
      EMAIL_SENDER_USERNAME: ""
      EMAIL_SENDER_PASSWORD: ""
      EMAIL_SENDER_HOST: ""
      SSL_TRUST_HOST: ""
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      PROXY_IP: ""
      MYSQL_USER_PATH: "/run/secrets/mysql_processor_user/mysql_processor_user"
      MYSQL_PASSWORD_PATH: "/run/secrets/mysql_processor_password/mysql_processor_user"
      NEO4J_USER_PATH: "/run/secrets/webapp_neo4j_user/webapp_neo4j_user"
      NEO4J_PASSWORD_PATH: "/run/secrets/webapp_neo4j_password/webapp_neo4j_password"
    deploy:
      labels:
        kompose.image-pull-policy: "Always"
      placement:
        constraints:
          - node.labels.role == node-a
  activemq:
    deploy:
      labels:
        kompose.image-pull-policy: "Always"
      placement:
        constraints:
          - node.labels.role == node-b
  kibana:
    deploy: 
      labels:
        kompose.image-pull-policy: "Always"
      placement:
        constraints:
          - node.labels.role == node-a
    # volumes:
    #   - ./gtas-parent/gtas-commons/certs:/etc/kibana/config/
  elasticsearch:
    deploy:
      labels:
        kompose.image-pull-policy: "Always"
      placement:
        constraints:
          - node.labels.role == node-b 
    # volumes:
    #   - /gtas-parent/gtas-commons/certs:/usr/share/elasticsearch/temp-cert
  mariadb:
    deploy:
      labels:
        kompose.image-pull-policy: "Always"
      placement:
        constraints:
          - node.labels.role == node-c
  logstash:
    deploy:
      labels:
        kompose.image-pull-policy: "Always"
      placement:
        constraints:
          - node.labels.role == node-b
    environment:
      XPACK_MONITORING_ELASTICSEARCH_SSL_CERTIFICATEAUTHORITY: /run/secrets/elastic-ca/elastic-ca
  elk-setup:
    deploy:
      labels:
        kompose.image-pull-policy: "Always"
      placement:
        constraints:
          - node.labels.role == node-b
    environment:
      LOGSTASH_PASSWORD_PATH: '/run/secrets/logstash-keystore-password/logstash-keystore-password' 
      MYSQL_USER_PATH: '/run/secrets/mysql-logstash-user/mysql-logstash-user'
      MYSQL_PASSWORD_PATH: '/run/secrets/mysql-logstash-password/mysql-logstash-password'
      KIBANA_PASSWORD_PATH: '/run/secrets/elasticsearch-kibana-password/elasticsearch-kibana-password'
      BOOTSTRAP_PATH: '/run/secrets/elastic-bootstrap-password/elastic-bootstrap-password'
      ELASTIC_PATH: '/run/secrets/elastic-password/elastic-password'
  neo4j:
    deploy:
      labels:
        kompose.image-pull-policy: "Always"
      placement:
        constraints:
          - node.labels.role == node-a
  etl-job:
    deploy:
      labels:
        kompose.image-pull-policy: "Always"
      placement:
        constraints:
          - node.labels.role == node-b
    environment:
      DB_HOSTNAME: mariadb
      NEO4J_USER_PATH: '/run/secrets/etl_neo4j_user/etl_neo4j_user'
      NEO4J_PASSWORD_PATH: '/run/secrets/etl_neo4j_password/etl_neo4j_password'
      MYSQL_USER_PATH: '/run/secrets/mysql_etl_user/mysql_etl_user'
      MYSQL_PASSWORD_PATH: '/run/secrets/mysql_etl_password/mysql_etl_password'

networks:
  gtas_webapp-network:
    driver: "overlay"
    attachable: true