version: '3.7'
services:
  http-proxy:
    labels:
      kompose.image-pull-policy: "Always" 
      kompose.service.type: "LoadBalancer"
    deploy:
      placement:
        constraints:
          - node.labels.role == frontend
    environment:
      BOOTSTRAP_PATH: '/run/secrets/elastic-bootstrap-password/elastic-bootstrap-password'
    volumes:
      - certs:/certs
  web-app:
    labels:
      kompose.image-pull-policy: "Always" 
      kompose.service.type: "LoadBalancer"
    environment:
      JAVA_TOOL_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport"
      JAVA_OPTS: "-Xms4g -Xmx8g -XX:MaxPermSize=16g -Duser.timezone=UTC"
      EMAIL_SENDER_USERNAME: ""
      EMAIL_SENDER_PASSWORD: ""
      EMAIL_SENDER_HOST: ""
      SSL_TRUST_HOST: ""
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      PROXY_IP: ""
      BOOTSTRAP_PATH: "/run/secrets/elastic-bootstrap-password/elastic-bootstrap-password"
      MYSQL_USER_PATH: "/run/secrets/mysql-webapp-user/mysql-webapp-user"
      MYSQL_PASSWORD_PATH: "/run/secrets/mysql-webapp-password/mysql-webapp-password"
      NEO4J_USER_PATH: "/run/secrets/webapp-neo4j-user/webapp-neo4j-user"
      NEO4J_PASSWORD_PATH: "/run/secrets/webapp-neo4j-password/webapp-neo4j-password"
      DB_HOST: ${MARIADB_HOST}
    deploy:
      placement:
        constraints:
          - node.labels.role == frontend
    volumes:
      - certs:/temp-cert
  gtas-scheduler:
    labels:
      kompose.image-pull-policy: "Always" 
      kompose.service.type: "LoadBalancer"
    ports:
      - 8081:8081
    environment:
      DB_HOST: ${MARIADB_HOST}
      JAVA_TOOL_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport"
      JAVA_OPTS: "-Xms8000m -Xmx16000m -Duser.timezone=UTC -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"
      EMAIL_SENDER_USERNAME: ""
      EMAIL_SENDER_PASSWORD: ""
      EMAIL_SENDER_HOST: ""
      SSL_TRUST_HOST: ""
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      PROXY_IP: ""
      MYSQL_USER_PATH: "/run/secrets/mysql-processor-user/mysql-processor-user"
      MYSQL_PASSWORD_PATH: "/run/secrets/mysql-processor-password/mysql-processor-password"
      NEO4J_USER_PATH: "/run/secrets/webapp-neo4j-user/webapp-neo4j-user"
      NEO4J_PASSWORD_PATH: "/run/secrets/webapp-neo4j-password/webapp-neo4j-password"
    deploy:
      placement:
        constraints:
          - node.labels.role == frontend
  activemq:
    labels:
      kompose.image-pull-policy: "Always" 
      kompose.service.type: "LoadBalancer"
    ports:
      - 61616:61616
    deploy:
      placement:
        constraints:
          - node.labels.role == frontend
  kibana:
    labels:
      kompose.image-pull-policy: "Always" 
      kompose.service.type: "LoadBalancer"
    deploy:
      placement:
        constraints:
          - node.labels.role == frontend
    volumes:
      - certs:/etc/kibana/config/
  elasticsearch:
    labels:
      kompose.image-pull-policy: "Always" 
      kompose.service.type: "LoadBalancer"
    deploy:
      placement:
        constraints:
          - node.labels.role == frontend
    volumes:
      - certs:/usr/share/elasticsearch/temp-cert
  mariadb:
    labels:
      kompose.image-pull-policy: "Always" 
      kompose.service.type: "LoadBalancer"
    deploy:
      placement:
        constraints:
          - node.labels.role == noRole
  logstash:
    labels:
      kompose.image-pull-policy: "Always" 
      kompose.service.type: "LoadBalancer"
    deploy:
      placement:
        constraints:
          - node.labels.role == frontend
    environment:
      MARIADB_HOST: ${MARIADB_HOST}
      XPACK_MONITORING_ELASTICSEARCH_SSL_CERTIFICATEAUTHORITY: /run/secrets/elastic-ca/elastic-ca
  elk-setup:
    labels:
      kompose.image-pull-policy: "Always" 
      kompose.service.type: "LoadBalancer"
    deploy:
      placement:
        constraints:
          - node.labels.role == frontend
    volumes:
      - certs:/usr/share/elasticsearch/config/certs/elasticsearch/
    environment:  
      LOGSTASH_PASSWORD_PATH: '/run/secrets/logstash-keystore-password/logstash-keystore-password' 
      MYSQL_USER_PATH: '/run/secrets/mysql-logstash-user/mysql-logstash-user'
      MYSQL_PASSWORD_PATH: '/run/secrets/mysql-logstash-password/mysql-logstash-password'
      KIBANA_PASSWORD_PATH: '/run/secrets/elasticsearch-kibana-password/elasticsearch-kibana-password'
      BOOTSTRAP_PATH: '/run/secrets/elastic-bootstrap-password/elastic-bootstrap-password'
      ELASTIC_PATH: '/run/secrets/elastic-password/elastic-password'
  neo4j:
    labels:
      kompose.image-pull-policy: "Always" 
      kompose.service.type: "LoadBalancer"
    deploy:
      placement:
        constraints:
          - node.labels.role == frontend
  etl-job:
    labels:
      kompose.image-pull-policy: "Always" 
      kompose.service.type: "LoadBalancer"
    deploy:
      placement:
        constraints:
          - node.labels.role == frontend
    environment:
      DB_HOSTNAME: ${MARIADB_HOST}
      NEO4J_USER_PATH: '/run/secrets/etl-neo4j-user/etl-neo4j-user'
      NEO4J_PASSWORD_PATH: '/run/secrets/etl-neo4j-password/etl-neo4j-password'
      MYSQL_USER_PATH: '/run/secrets/mysql-etl-user/mysql-etl-user'
      MYSQL_PASSWORD_PATH: '/run/secrets/mysql-etl-password/mysql-etl-password'
networks:
  gtas_webapp-network:
    attachable: true