version: '3.7'
services:
  http-proxy:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-webapp-node
    environment:
      BOOTSTRAP_PATH: '/run/secrets/elastic-bootstrap-password'
  web-app:
    environment:
      JAVA_TOOL_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport"
      JAVA_HOME: "/usr/local/gtas-java-jre"
      JAVA_OPTS: "-Xms4g -Xmx8g -XX:MaxPermSize=16g -Duser.timezone=UTC"
      EMAIL_SENDER_USERNAME: ""
      EMAIL_SENDER_PASSWORD: ""
      EMAIL_SENDER_HOST: ""
      SSL_TRUST_HOST: ""
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      PROXY_IP: ""
      BOOTSTRAP_PATH: "/run/secrets/elastic-bootstrap-password"
      MYSQL_USER_PATH: "/run/secrets/mysql_webapp_user"
      MYSQL_PASSWORD_PATH: "/run/secrets/mysql_webapp_password"
      NEO4J_USER_PATH: "/run/secrets/webapp_neo4j_user"
      NEO4J_PASSWORD_PATH: "/run/secrets/webapp_neo4j_password"
    volumes:
      - type: bind
        source: /mnt/gtas-java-jre
        target: /usr/local/gtas-java-jre
      - type: bind
        source: /var/opt/gtas_web_app_application_properties
        target: /usr/local/tomcat/conf
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-webapp-node
  gtas-scheduler:
    environment:
      JAVA_TOOL_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport"
      JAVA_HOME: "/usr/local/gtas-java-jre"
      JAVA_OPTS: "-Xms8000m -Xmx16000m -Duser.timezone=UTC -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"
      EMAIL_SENDER_USERNAME: ""
      EMAIL_SENDER_PASSWORD: ""
      EMAIL_SENDER_HOST: ""
      SSL_TRUST_HOST: ""
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      PROXY_IP: ""
      MYSQL_USER_PATH: "/run/secrets/mysql_processor_user"
      MYSQL_PASSWORD_PATH: "/run/secrets/mysql_processor_password"
      NEO4J_USER_PATH: "/run/secrets/webapp_neo4j_user"
      NEO4J_PASSWORD_PATH: "/run/secrets/webapp_neo4j_password"
    volumes:
      - type: bind
        source: /mnt/gtas-java-jre
        target: /usr/local/gtas-java-jre
      - type: bind
        source: /var/opt/gtas_scheduler_application_properties
        target: /usr/local/tomcat/conf
      - type: bind
        source: /mnt
        target: /usr/local/gtas-data
        consistency: consistent
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-messenger-node
  activemq:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-neo4j-node
  mariadb:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-db-node
  kibana:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-elk-node
  elasticsearch:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-elk-node
  logstash:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-elk-node
    environment:
      XPACK_MONITORING_ELASTICSEARCH_SSL_CERTIFICATEAUTHORITY: /run/secrets/elastic-ca
  elk-setup:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-elk-node
    environment:
      LOGSTASH_PASSWORD_PATH: '/run/secrets/logstash-keystore-password' 
      MYSQL_USER_PATH: '/run/secrets/mysql-logstash-user'
      MYSQL_PASSWORD_PATH: '/run/secrets/mysql-logstash-password'
      KIBANA_PASSWORD_PATH: '/run/secrets/elasticsearch-kibana-password'
      BOOTSTRAP_PATH: '/run/secrets/elastic-bootstrap-password'
      ELASTIC_PATH: '/run/secrets/elastic-password'
  neo4j:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-neo4j-node
  etl-job:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-neo4j-node
    environment:
      DB_HOSTNAME: mariadb
      NEO4J_USER_PATH: '/run/secrets/etl_neo4j_user'
      NEO4J_PASSWORD_PATH: '/run/secrets/etl_neo4j_password'
      MYSQL_USER_PATH: '/run/secrets/mysql_etl_user'
      MYSQL_PASSWORD_PATH: '/run/secrets/mysql_etl_password'

networks:
  GTAS-webapp-network:
    driver: "overlay"
    attachable: true