version: '3.7'
services:
  http-proxy:
    deploy:
      placement:
        constraints:
          - node.hostname == gtasp2
  web-app:
    environment:
      JAVA_TOOL_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport"
      # JAVA_HOME: "/usr/local/gtas-java-jre"
      JAVA_OPTS: "-Xms4g -Xmx8g -XX:MaxPermSize=16g -Duser.timezone=UTC"
      EMAIL_SENDER_USERNAME: "test"
      EMAIL_SENDER_PASSWORD: "test"
      EMAIL_SENDER_HOST: "test"
      SSL_TRUST_HOST: "test"
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      PROXY_IP: "10.137.27.61"
    volumes:
      # - type: bind
      #   source: /mnt/gtas-java-jre
      #   target: /usr/local/gtas-java-jre
      - type: bind
        source: /var/opt/gtas_web_app_application_properties
        target: /usr/local/tomcat/conf
    deploy:
      placement:
        constraints:
          - node.hostname == gtasp2
  gtas-scheduler:
    environment:
      JAVA_TOOL_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport"
      # JAVA_HOME: "/usr/local/gtas-java-jre"
      JAVA_OPTS: "-Xms8000m -Xmx16000m -Duser.timezone=UTC -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"
      EMAIL_SENDER_USERNAME: "test"
      EMAIL_SENDER_PASSWORD: "test"
      EMAIL_SENDER_HOST: "test"
      SSL_TRUST_HOST: "test"
      AUTOMATED_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      MANUAL_HIT_NOTIFICATION_EMAIL_ENABLED: "false"
      PROXY_IP: "10.137.27.61"
    volumes:
      # - type: bind
      #   source: /mnt/gtas-java-jre
      #   target: /usr/local/gtas-java-jre
      - type: bind
        source: /var/opt/gtas_scheduler_application_properties
        target: /usr/local/tomcat/conf
      - type: bind
        source: /mnt
        target: /usr/local/gtas-data
        consistency: consistent
    deploy:
      placement:
        constraints:
          - node.hostname == gtasp2
  activemq:
    deploy:
      placement:
        constraints:
          - node.hostname == gtasp2
  mariadb:
    deploy:
      placement:
        constraints:
          - node.hostname == gtasp1
  kibana:
    deploy:
      placement:
        constraints:
          - node.hostname == gtasp3
  elasticsearch:
    deploy:
      placement:
        constraints:
          - node.hostname == gtasp3
  logstash:
    deploy:
      placement:
        constraints:
          - node.hostname == gtasp3
  elk-setup:
    deploy:
      placement:
        constraints:
          - node.hostname == gtasp3
  neo4j:
    deploy:
      placement:
        constraints:
          - node.hostname == gtasp2

networks:
  GTAS_webapp-network:
    driver: "overlay"
    attachable: true